### ISSUE TITLE
异步无法重连

### ISSUE THREAD

**Issue by Princebin** [RRQM/RRQMSocket#2]
TCPClient使用ConnectAsync连接服务端，服务端立即重启，TCPClient在在断开事件中，再次调用ConnectAsync连接服务端，没有任何反应，无法连接服务端

**Comment by RRQM** [comment]
感谢您的反馈，我尽快核查情况

**Comment by RRQM** [comment]
再次感谢您的反馈，经排查，二次连接确实有bug存在，目前已经修复，但是并未发布到nuget，预计今天21:00之前发布，请注意更新。

同时，也修复了RRQM的自带的断线重连，调用以下代码即可实现。

`tcpClient.UseReconnection(tryCount:5,printLog:true);`
